package com.example.booklist

import androidx.annotation.DrawableRes


data class Book(
    val id: Int,
    val name: String,
    val author: String,
    val publishDate: String,
    val edition: String,
    val numPages: Int,
    val summary: String,
    @DrawableRes val imageId: Int
)

val books = listOf(
    Book(
        0,
        "Harry Potter and the Philosopher's Stone",
        "J. K. Rowling",
        "26 June 1997",
        "first edition",
        223,
        "Harry Potter lives with his abusive aunt and uncle, Vernon and Petunia Dursley and their bullying son, Dudley. On Harry's eleventh birthday, a half-giant named Rubeus Hagrid personally delivers an acceptance letter to Hogwarts School of Witchcraft and Wizardry, revealing that Harry's parents, James and Lily Potter, were wizards. When Harry was one year old, an evil and powerful dark wizard, Lord Voldemort, murdered his parents. Harry survived Voldemort's killing curse that rebounded off his forehead and seemingly destroyed the Dark Lord, leaving a lightning bolt-shaped scar on his forehead. Unknown to Harry, he is famous in the wizarding world.",
        R.drawable.philosophers_stone,
    ),
    Book(
        1,
        "Harry Potter and the Chamber of Secrets",
        "J. K. Rowling",
        "2 July 1998",
        "first edition",
        251,
        "While spending the summer at the Dursleys, twelve-year-old Harry Potter is visited by a house-elf named Dobby. He warns that Harry is in danger and must not return to Hogwarts. Harry refuses, so Dobby magically ruins Aunt Petunia and Uncle Vernon's dinner party. A furious Uncle Vernon locks Harry into his room in retaliation. The Ministry of Magic immediately sends a notice accusing Harry of performing underage magic and threatening dismissal from Hogwarts.",
        R.drawable.chamber_of_secrets,
    ),
    Book(
        2,
        "Harry Potter and the Prisoner of Azkaban",
        "J. K. Rowling",
        "8 July 1999",
        "first edition",
        317,
        "Thirteen-year-old Harry Potter spends another unhappy summer at the Dursleys. After Aunt Marge insults Harry and his deceased parents, an angry Harry accidentally inflates her. Fearing expulsion from Hogwarts, he runs away. The Knight Bus, a vehicle that rescues stranded wizards, suddenly arrives. Harry encounters the Minister of Magic, Cornelius Fudge, at the Leaky Cauldron in Diagon Alley, where Fudge asks Harry to remain until school starts. Harry reunites with best friends, Ron Weasley and Hermione Granger. Ron's father warns Harry about the wizard Sirius Black, a convicted murderer who escaped Azkaban and is believed to be hunting down Harry.",
        R.drawable.prisoner_of_azkaban,
    ),
    Book(
        3,
        "Harry Potter and the Goblet of Fire",
        "J. K. Rowling",
        "8 July 2000",
        "first edition",
        636,
        "In a prologue, which Harry sees through a dream, Frank Bryce, Muggle caretaker of an abandoned mansion known as the Riddle House, is murdered by Lord Voldemort after stumbling upon him and Wormtail. Harry is awoken by his scar hurting.",
        R.drawable.goblet_of_fire,
    ),
    Book(
        4,
        "Harry Potter and the Order of the Phoenix",
        "J. K. Rowling",
        "21 June 2003",
        "first edition",
        766,
        "During the summer, Harry Potter and his cousin Dudley are attacked by Dementors. Forced to magically fend them off, Harry is expelled from Hogwarts, but his expulsion is postponed pending a hearing at the Ministry of Magic. A group of wizards belonging to the Order of the Phoenix whisk Harry off to Number 12, Grimmauld Place, Sirius Black's childhood home.",
        R.drawable.order_of_the_phoenix,
    ),
    Book(
        5,
        "Harry Potter and the Half-Blood Prince",
        "J. K. Rowling",
        "16 July 2005",
        "first edition",
        607,
        "Severus Snape, a member of the Order of the Phoenix, meets with Narcissa Malfoy, Draco's mother, and her sister Bellatrix Lestrange, Lord Voldemort's supporter. Narcissa expresses concern that her son may not survive a mission that Voldemort has given him. Snape makes an Unbreakable Vow with Narcissa, swearing to assist Draco.",
        R.drawable.half_blood_prince,
    ),
    Book(
        6,
        "Harry Potter and the Deathly Hallows",
        "J. K. Rowling",
        "21 July 2007",
        "first edition",
        607,
        "Throughout the six previous novels in the series, the main character Harry Potter has struggled with the difficulties of adolescence along with being famous as the only person ever to survive the Killing Curse. The curse was cast by Tom Riddle, better known as Lord Voldemort, a powerful evil wizard who murdered Harry's parents and attempted to kill Harry as a baby, due to a prophecy which claimed Harry would be able to stop him. As an orphan, Harry was placed in the care of his Muggle (non-magical) relatives Petunia Dursley and Vernon Dursley, with their son Dudley Dursley.",
        R.drawable.deathly_hallows,
    ),
    Book(
        7,
        "Harry Potter and the Cursed Child",
        "J. K. Rowling",
        "30 July 2016",
        "first edition",
        270,
        "In the opening scene, set during the epilogue of Deathly Hallows in the year 2017, Harry and Ginny Potter send their younger son, Albus Severus, on the Hogwarts Express to begin his first year at Hogwarts. Harry works as the Head of Magical Law Enforcement at the Ministry of Magic, while Ginny is the editor of the sports section of The Daily Prophet. Ron Weasley and Hermione Granger also send their daughter Rose on the train. Hermione is now Minister for Magic, while Ron manages Weasley's Wizard Wheezes in Diagon Alley alongside his brother George. Aboard the Hogwarts Express, Albus befriends Scorpius Malfoy, the son of Harry's former nemesis Draco and his wife Astoria. In a break with the tradition of Potters being sorted into Gryffindor, Albus is sorted into Slytherin alongside Scorpius.",
        R.drawable.cursed_child,
    ),
    Book(
        8,
        "The Tales of Beedle the Bard",
        "J. K. Rowling",
        "13 December 2007",
        "first edition",
        157,
        "The Tales of Beedle the Bard is a book of children's stories by the author J. K. Rowling. There is a storybook of the same name mentioned in Harry Potter and the Deathly Hallows, the last book of the Harry Potter series.",
        R.drawable.beedle_the_bard,
    ),
    Book(
        8,
        "The Tales of Beedle the Bard",
        "J. K. Rowling",
        "13 December 2007",
        "first edition",
        157,
        "The Tales of Beedle the Bard is a book of children's stories by the author J. K. Rowling. There is a storybook of the same name mentioned in Harry Potter and the Deathly Hallows, the last book of the Harry Potter series.",
        R.drawable.beedle_the_bard,
    ),
)
